---
- name: Sample IOS config for Ansible 2.5+
  hosts: all
  gather_facts: no

  tasks:

  - name: Create loopback 20
    ios_interface:
      name: Loopback 20
      enabled: True
      description: Created with Ansible
  - name: Assign IP to loopback
    ios_l3_interface:
      name: Loopback 20
      ipv4: "192.168.25.1/24"
