---
- name: get arp info
  hosts: all
  gather_facts: false

- name: get arp info
  hosts: all
  gather_facts: false


  tasks:
   - name: show ip interfaces
     raw: "show ip interfaces brief"


     register: print_output


   - debug: var=print_output.stdout_lines
