---
- name: get arp info
  hosts: all
  gather_facts: false

  tasks:
   - name: show ip interfaces
     raw: "show ip interfaces brief"
     register: out

   - debug: var=out.stdout_lines
    
   - name: run the command 'show version'
     cisco.ios.ios_command:
      commands:
      - show version
      - show interfaces
      wait_for:
      - result[0] contains IOS
      - result[1] contains Loopback0
